# common configuration for ALL branches
image: Visual Studio 2017
install:
  - choco install gitversion.portable -y
test: off
assembly_info:
  patch: false
nuget:
  disable_publish_on_pr: true
environment:
  apiKey:
    secure: 1gZfYXDnZKFT1JddFudQ6YWtaY3b5dd9TRyGgMWAvDcaemYinhdGIzRa21VKSGx5
before_build:
  - ps: gitversion /l console /output buildserver
  - nuget setapikey %apiKey% -Verbosity quiet
build_script:
  - cmd: set BUILD_TARGET=Package
  - cmd: if "%APPVEYOR_REPO_TAG%" == "true" set BUILD_TARGET=Deploy
  - cmd: build.bat /t:CoverageUpload;%BUILD_TARGET% /v:m